require './logo@150.png'
# require './focus_1.jpg'
# require './focus_2.jpg'
require './focus_3.jpg'
require './focus_en.jpg'
require './vidposter.jpg'
require './blank.gif'
require './flags.png'

# robots
require './r1.png'
require './r2.png'
require './r3.png'
require './r4.png'
require './r5.png'

# icons
require 'file-loader?name=images/icons/[name].[ext]!./icons/android-icon-36x36.png'
require 'file-loader?name=images/icons/[name].[ext]!./icons/android-icon-48x48.png'
require 'file-loader?name=images/icons/[name].[ext]!./icons/android-icon-72x72.png'
require 'file-loader?name=images/icons/[name].[ext]!./icons/android-icon-96x96.png'
require 'file-loader?name=images/icons/[name].[ext]!./icons/android-icon-144x144.png'
require 'file-loader?name=images/icons/[name].[ext]!./icons/android-icon-192x192.png'
require 'file-loader?name=images/icons/[name].[ext]!./icons/apple-icon-57x57.png'
require 'file-loader?name=images/icons/[name].[ext]!./icons/apple-icon-60x60.png'
require 'file-loader?name=images/icons/[name].[ext]!./icons/apple-icon-72x72.png'
require 'file-loader?name=images/icons/[name].[ext]!./icons/apple-icon-76x76.png'
require 'file-loader?name=images/icons/[name].[ext]!./icons/apple-icon-114x114.png'
require 'file-loader?name=images/icons/[name].[ext]!./icons/apple-icon-120x120.png'
require 'file-loader?name=images/icons/[name].[ext]!./icons/apple-icon-144x144.png'
require 'file-loader?name=images/icons/[name].[ext]!./icons/apple-icon-152x152.png'
require 'file-loader?name=images/icons/[name].[ext]!./icons/apple-icon-180x180.png'
require 'file-loader?name=images/icons/[name].[ext]!./icons/apple-icon-precomposed.png'
require 'file-loader?name=images/icons/[name].[ext]!./icons/apple-icon.png'
require 'file-loader?name=images/icons/[name].[ext]!./icons/favicon-16x16.png'
require 'file-loader?name=images/icons/[name].[ext]!./icons/favicon-32x32.png'
require 'file-loader?name=images/icons/[name].[ext]!./icons/favicon-96x96.png'
require 'file-loader?name=images/icons/[name].[ext]!./icons/ms-icon-70x70.png'
require 'file-loader?name=images/icons/[name].[ext]!./icons/ms-icon-144x144.png'
require 'file-loader?name=images/icons/[name].[ext]!./icons/ms-icon-150x150.png'
require 'file-loader?name=images/icons/[name].[ext]!./icons/ms-icon-310x310.png'
# require './browserconfig.xml'

# team
require 'file-loader?name=images/team/[name].[ext]!./team/gulu.jpg'
require 'file-loader?name=images/team/[name].[ext]!./team/wangxiaoying.jpg'
require 'file-loader?name=images/team/[name].[ext]!./team/alien.jpg'
require 'file-loader?name=images/team/[name].[ext]!./team/qijun.jpg'
require 'file-loader?name=images/team/[name].[ext]!./team/xiaolai.jpg'
require 'file-loader?name=images/team/[name].[ext]!./team/chuxiahu.jpg'
require 'file-loader?name=images/team/[name].[ext]!./team/dashan.jpg'
require 'file-loader?name=images/team/[name].[ext]!./team/juxie.jpg'
require 'file-loader?name=images/team/[name].[ext]!./team/baicai.jpg'
require 'file-loader?name=images/team/[name].[ext]!./team/chenshixin.jpg'
require 'file-loader?name=images/team/[name].[ext]!./team/yangbo.jpg'
require 'file-loader?name=images/team/[name].[ext]!./team/gaoqingzhong.jpg'
require 'file-loader?name=images/team/[name].[ext]!./team/lisong.jpg'
require 'file-loader?name=images/team/[name].[ext]!./team/qianxiaodong.jpg'
require 'file-loader?name=images/team/[name].[ext]!./team/zhuzhaohui.jpg'
require 'file-loader?name=images/team/[name].[ext]!./team/zhouqian.jpg'
require 'file-loader?name=images/team/[name].[ext]!./team/ray.jpg'
require 'file-loader?name=images/team/[name].[ext]!./team/julian.jpg'
require 'file-loader?name=images/team/[name].[ext]!./team/caroline.jpg'
require 'file-loader?name=images/team/[name].[ext]!./team/liubin.jpg'
require 'file-loader?name=images/team/[name].[ext]!./team/liujun.jpg'
require 'file-loader?name=images/team/[name].[ext]!./team/dengdi.jpg'
require 'file-loader?name=images/team/[name].[ext]!./team/zhangshousong.jpg'
require 'file-loader?name=images/team/[name].[ext]!./team/hanfeng.jpg'
require 'file-loader?name=images/team/[name].[ext]!./team/zhupinpin.jpg'
require 'file-loader?name=images/team/[name].[ext]!./team/yaotianfang.jpg'
require 'file-loader?name=images/team/[name].[ext]!./team/huangheyan.jpg'
require 'file-loader?name=images/team/[name].[ext]!./team/meihong.jpg'
require 'file-loader?name=images/team/[name].[ext]!./team/zhoushuoji.jpg'
require 'file-loader?name=images/team/[name].[ext]!./team/jizhoudong.jpg'
require 'file-loader?name=images/team/[name].[ext]!./team/laomao.jpg'
require 'file-loader?name=images/team/[name].[ext]!./team/huangtianwei.jpg'
require 'file-loader?name=images/team/[name].[ext]!./team/inb.jpg'

# contrib
require 'file-loader?name=images/contrib/mew/[name].[ext]!./contrib/mew/mew-1.png'
require 'file-loader?name=images/contrib/mew/[name].[ext]!./contrib/mew/mew-2.png'
require 'file-loader?name=images/contrib/mew/[name].[ext]!./contrib/mew/mew-3.png'
require 'file-loader?name=images/contrib/mew/[name].[ext]!./contrib/mew/mew-4.png'
require 'file-loader?name=images/contrib/mew/[name].[ext]!./contrib/mew/mew-5.png'
require 'file-loader?name=images/contrib/mew/[name].[ext]!./contrib/mew/mew-6.png'
require 'file-loader?name=images/contrib/mew/[name].[ext]!./contrib/mew/mew-7.png'
require 'file-loader?name=images/contrib/mew/[name].[ext]!./contrib/mew/mew-8.png'
require 'file-loader?name=images/contrib/mew/[name].[ext]!./contrib/mew/mew-9.png'
require 'file-loader?name=images/contrib/mew/[name].[ext]!./contrib/mew/mew-10.png'

require 'file-loader?name=images/contrib/imtoken/[name].[ext]!./contrib/imtoken/imtoken-1.jpg'
require 'file-loader?name=images/contrib/imtoken/[name].[ext]!./contrib/imtoken/imtoken-2.jpg'
require 'file-loader?name=images/contrib/imtoken/[name].[ext]!./contrib/imtoken/imtoken-3.jpg'
require 'file-loader?name=images/contrib/imtoken/[name].[ext]!./contrib/imtoken/imtoken-4.jpg'
require 'file-loader?name=images/contrib/imtoken/[name].[ext]!./contrib/imtoken/imtoken-5.png'

require 'file-loader?name=images/contrib/bts/[name].[ext]!./contrib/bts/bts.jpg'